### ISSUE TITLE
Use dirname(__FILE__) instead to call new instance

### ISSUE THREAD

**Issue by ipoweb** [jazzsequence/Strict-Gravity-Forms---Custom-Post-Types#1]
i think it would be better to call dirname(**FILE**) instead to call new instance

//include the base class
            require_once(dirname(**FILE**) . '/gfcptaddonbase.php');

```
        //only supports 1.5 and over
        require_once(dirname(__FILE__) . '/gfcptaddon_1-5.php');
```

**Comment by jazzsequence** [comment]
Yeah, good point. Then you eliminate PHP incompatibility altogether because you aren't trying to call an instance.

**Comment by ipoweb** [comment]
yep :)
Thanks
